/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-17-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Dubliners {
    public static void add(Integer i, Integer j) 
    {
       Integer k = i+j;
       System.debug('result of addition'+k);
    }
    public static void substraction(Integer i, Integer j) 
    {
       Integer k = i-j;
       System.debug('result of substraction'+k);
    }
    public static void multiply(Integer i, Integer j) 
    {
       Integer k = i*j;
       System.debug('result of Multiplication'+k);
    }
    public static void divide(Integer i, Integer j) 
    {
       Integer k = i/j;
       System.debug('result of div'+k);
    }
}

